/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteRouteImport } from './routes/_main-layout/route'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutPrivacyRouteImport } from './routes/_main-layout/privacy'
import { Route as MainLayoutWorkSonicEquipmentIndexRouteImport } from './routes/_main-layout/work/sonic-equipment/index'

const MainLayoutRouteRoute = MainLayoutRouteRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutPrivacyRoute = MainLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainLayoutRouteRoute,
} as any)
const MainLayoutWorkSonicEquipmentIndexRoute =
  MainLayoutWorkSonicEquipmentIndexRouteImport.update({
    id: '/work/sonic-equipment/',
    path: '/work/sonic-equipment/',
    getParentRoute: () => MainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof MainLayoutPrivacyRoute
  '/': typeof MainLayoutIndexRoute
  '/work/sonic-equipment': typeof MainLayoutWorkSonicEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof MainLayoutPrivacyRoute
  '/': typeof MainLayoutIndexRoute
  '/work/sonic-equipment': typeof MainLayoutWorkSonicEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteRouteWithChildren
  '/_main-layout/privacy': typeof MainLayoutPrivacyRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/work/sonic-equipment/': typeof MainLayoutWorkSonicEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/privacy' | '/' | '/work/sonic-equipment'
  fileRoutesByTo: FileRoutesByTo
  to: '/privacy' | '/' | '/work/sonic-equipment'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/privacy'
    | '/_main-layout/'
    | '/_main-layout/work/sonic-equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRouteRoute: typeof MainLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_main-layout/privacy': {
      id: '/_main-layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainLayoutPrivacyRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
    '/_main-layout/work/sonic-equipment/': {
      id: '/_main-layout/work/sonic-equipment/'
      path: '/work/sonic-equipment'
      fullPath: '/work/sonic-equipment'
      preLoaderRoute: typeof MainLayoutWorkSonicEquipmentIndexRouteImport
      parentRoute: typeof MainLayoutRouteRoute
    }
  }
}

interface MainLayoutRouteRouteChildren {
  MainLayoutPrivacyRoute: typeof MainLayoutPrivacyRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutWorkSonicEquipmentIndexRoute: typeof MainLayoutWorkSonicEquipmentIndexRoute
}

const MainLayoutRouteRouteChildren: MainLayoutRouteRouteChildren = {
  MainLayoutPrivacyRoute: MainLayoutPrivacyRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutWorkSonicEquipmentIndexRoute:
    MainLayoutWorkSonicEquipmentIndexRoute,
}

const MainLayoutRouteRouteWithChildren = MainLayoutRouteRoute._addFileChildren(
  MainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRouteRoute: MainLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
